trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .pipeline/PhotoCarousel-Display.yml
    - PhotoCarousel/PhotoCarousel.Display/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK (7.0.202)'
  inputs:
    packageType: sdk
    version: 7.0.202
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: | 
      **/PhotoCarousel.Display.csproj

- task: DotNetCoreCLI@2
  displayName: Build PhotoCarousel.Display.csproj
  inputs:
    command: 'build'
    projects: | 
      **/PhotoCarousel.Display.csproj

- script: |
    dotnet publish ./PhotoCarousel/PhotoCarousel.Display --configuration "Release" --runtime linux-arm --output ./PhotoCarousel/PhotoCarousel.Display/bin/Release/publish

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/PhotoCarousel/PhotoCarousel.Display/bin/Release/publish' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/PhotoCarousel.Display.zip' 

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: PhotoCarousel.Display