trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .pipeline/PhotoCarousel-Worker.yml
    - PhotoCarousel/PhotoCarousel.Worker/*
    - PhotoCarousel/PhotoCarousel.Common/*
    - PhotoCarousel/PhotoCarousel.Enums/*
    - PhotoCarousel/PhotoCarousel.Entities/*
    - PhotoCarousel/PhotoCarousel.Contracts/*
    - PhotoCarousel/PhotoCarousel.DataAccess/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK (7.0.202)'
  inputs:
    packageType: sdk
    version: 7.0.202
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: | 
      **/PhotoCarousel.Worker.csproj
- task: DotNetCoreCLI@2
  displayName: Build PhotoCarousel.Worker.csproj
  inputs:
    command: 'build'
    projects: | 
      **/PhotoCarousel.Worker.csproj
- script: |
    cd ./PhotoCarousel
    docker build -t djohnnie/photocarousel-worker -f Dockerfile-Worker .
    docker login -u '$(dockerId)' -p '$(dockerPwd)'
    docker push djohnnie/photocarousel-worker
  displayName: Build & Push djohnnie/photocarousel-worker