name: $(Date:yyyy).$(Date:MM).$(Date:dd).$(Build.BuildId)

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .pipeline/PhotoCarousel-Browser.yml
    - PhotoCarousel/PhotoCarousel.Enums/*
    - PhotoCarousel/PhotoCarousel.Contracts/*
    - PhotoCarousel/PhotoCarousel.Browser/*

pool:
  vmImage: 'windows-latest'

steps:
- script: echo '$(Build.BuildNumber)'

- task: UseDotNet@2
  displayName: 'Use .NET SDK (6.0.101)'
  inputs:
    packageType: sdk
    version: 6.0.101
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet
  
- task: PowerShell@2
  displayName: 'Inno setup download'
  inputs:
    targetType: 'inline'
    script: 'choco install innosetup'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: | 
      **/PhotoCarousel.Browser.csproj

- task: DotNetCoreCLI@2
  displayName: Build PhotoCarousel.Browser.csproj
  inputs:
    command: 'build'
    projects: | 
      **/PhotoCarousel.Browser.csproj

- script: |
    dotnet publish ./PhotoCarousel/PhotoCarousel.Browser --configuration "Release" --runtime win10-x64 --output ./PhotoCarousel/PhotoCarousel.Browser/bin/Release/publish /p:AssemblyVersion=$(Build.BuildNumber)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/PhotoCarousel/PhotoCarousel.Browser/bin/Release/publish' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/PhotoCarousel.Browser.zip' 

- task: PowerShell@2
  displayName: 'Execute Inno Setup script'
  inputs:
    targetType: 'inline'
    script: 'iscc.exe $(Build.SourcesDirectory)/PhotoCarousel/PhotoCarousel.Browser/setup.iss /DMyAppVersion=$(Build.BuildNumber)'

- task: CopyFiles@2
  displayName: 'Copy setup to artifact'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/PhotoCarousel/PhotoCarousel.Browser/Output'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: PhotoCarousel.Browser

- task: AzureFileCopy@4
  inputs:
    sourcePath: '$(Build.SourcesDirectory)/PhotoCarousel/PhotoCarousel.Browser/Output/PhotoCarousel.Browser.$(Build.BuildNumber).Setup.exe'
    azureSubscription: 'djohnnieke-storage'
    destination: AzureBlob
    storage: djohnnieke
    containerName: 'photo-carousel'