trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK (5.0)'
  inputs:
    packageType: sdk
    version: 5.0.400
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: | 
      **/PhotoCarousel.Api.csproj
- task: DotNetCoreCLI@2
  displayName: Build PhotoCarousel.Api.csproj
  inputs:
    command: 'build'
    projects: | 
      **/PhotoCarousel.Api.csproj
- script: |
    cd ./PhotoCarousel
    docker build -t djohnnie/photocarousel-api Dockerfile-Api
    docker login -u $(dockerId) -p $(dockerPwd)
    docker push djohnnie/photocarousel-api
  displayName: Build & Push djohnnie/photocarousel-api