FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
RUN apt-get update && apt-get install -y apt-utils libgdiplus libc6-dev
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["PhotoCarousel.Backend.sln", "./"]
COPY ["PhotoCarousel.Common/*.csproj", "./PhotoCarousel.Common/"]
COPY ["PhotoCarousel.Enums/*.csproj", "./PhotoCarousel.Enums/"]
COPY ["PhotoCarousel.Entities/*.csproj", "./PhotoCarousel.Entities/"]
COPY ["PhotoCarousel.Contracts/*.csproj", "./PhotoCarousel.Contracts/"]
COPY ["PhotoCarousel.DataAccess/*.csproj", "./PhotoCarousel.DataAccess/"]
COPY ["PhotoCarousel.Worker/*.csproj", "./PhotoCarousel.Worker/"]
COPY ["PhotoCarousel.Api/*.csproj", "./PhotoCarousel.Api/"]

RUN dotnet restore
COPY . .
WORKDIR "/src/PhotoCarousel.Common"
RUN dotnet build "PhotoCarousel.Common.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.Enums"
RUN dotnet build "PhotoCarousel.Enums.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.Entities"
RUN dotnet build "PhotoCarousel.Entities.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.Contracts"
RUN dotnet build "PhotoCarousel.Contracts.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.DataAccess"
RUN dotnet build "PhotoCarousel.DataAccess.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.Api"
RUN dotnet build "PhotoCarousel.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PhotoCarousel.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 5000

ENV TZ=Europe/Brussels
ENV DB_CONNECTION_STRING=...
ENV PHOTO_SLIDESHOW_DURATION=...
ENV CERTIFICATE_FILENAME=...
ENV CERTIFICATE_PASSWORD=...

ENTRYPOINT ["dotnet", "PhotoCarousel.Api.dll"]