FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
RUN apt-get update && apt-get install -y apt-utils libgdiplus libc6-dev
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["PhotoCarousel.Backend.sln", "./"]
COPY ["PhotoCarousel.Common/*.csproj", "./PhotoCarousel.Common/"]
COPY ["PhotoCarousel.Entities/*.csproj", "./PhotoCarousel.Entities/"]
COPY ["PhotoCarousel.DataAccess/*.csproj", "./PhotoCarousel.DataAccess/"]
COPY ["PhotoCarousel.Worker/*.csproj", "./PhotoCarousel.Worker/"]
COPY ["PhotoCarousel.Api/*.csproj", "./PhotoCarousel.Api/"]

RUN dotnet restore
COPY . .
WORKDIR "/src/PhotoCarousel.Common"
RUN dotnet build "PhotoCarousel.Common.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.Entities"
RUN dotnet build "PhotoCarousel.Entities.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.DataAccess"
RUN dotnet build "PhotoCarousel.DataAccess.csproj" -c Release -o /app/build
WORKDIR "/src/PhotoCarousel.Worker"
RUN dotnet build "PhotoCarousel.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PhotoCarousel.Worker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV TZ=Europe/Brussels
ENV DB_CONNECTION_STRING=...
ENV PHOTO_ROOT_PATH=...
ENV THUMBNAIL_PATH=...
ENV INDEXER_INTERVAL_IN_SECONDS=...
ENV THUMBNAIL_INTERVAL_IN_SECONDS=...
ENV THUMBNAIL_SIZE=...

ENTRYPOINT ["dotnet", "PhotoCarousel.Worker.dll"]